services:
  - type: web
    name: socialyt-app
    env: docker
    port: 80
    plan: free
    region: singapore
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        fromContext: "https://socialyt-app.onrender.com"
      - key: DB_CONNECTION
        value: mysql
      # Add your DB credentials here after creating a MySQL instance on Render
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
    # Specify the port Apache is listening on
    healthCheckPath: /
    numInstances: 1
